### ISSUE TITLE
no segment3 in newest ndnts library

### ISSUE THREAD

**Issue by killerdbob** [yoursunny/NDNts-video#1]
hi, I download the newest ndnts library, and I could not find name convention3 in the library
![image](https://user-images.githubusercontent.com/25005010/146472451-8a76f414-eb82-4067-b965-1668765f4d88.png)
![image](https://user-images.githubusercontent.com/25005010/146472564-ab1cd85c-fcc8-4ac6-bd5c-8cfb10caa602.png)
![image](https://user-images.githubusercontent.com/25005010/146473391-8d6513a2-a9b3-4ac4-8bed-fffccb152abc.png)

**Comment by yoursunny** [comment]
Please provide all error messages as text, not as pictures.

**Comment by killerdbob** [comment]
Ok, I figure it out, I must run 'yarn cache clean', otherwise the yarn will use caching file of ndnts. Finally, it works.

**Comment by yoursunny** [comment]
> otherwise the yarn will use caching file of ndnts

That's a shortcoming of NDNts-nightly.
https://yoursunny.com/t/2020/NDNts-nightly/
